/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#fff3f0',
          100: '#ffdad2',
          300: '#ffb4a3',
          500: '#b3543d',
          600: '#943d28',
          700: '#7d2c18',
          950: '#3d0700',
        },
        mint: {
          50: '#eef8f0',
          100: '#c8ebd0',
          500: '#4b6a54',
          600: '#466550',
        },
        earth: {
          50: '#fdf9f4',
          100: '#f7f3ee',
          200: '#f1ede8',
          300: '#e6e2dd',
          400: '#dcc1ba',
          500: '#89726d',
          700: '#56423e',
          900: '#1c1c19',
        },
        amber: {
          50: '#fff4e8',
          100: '#ffdeac',
          500: '#956800',
          700: '#5f4100',
        },
        ink: '#1c1c19',
        canvas: '#fdf9f4',
        background: '#fdf9f4',
        surface: '#ffffff',
        'surface-bright': '#fdf9f4',
        'surface-dim': '#ddd9d5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f7f3ee',
        'surface-container': '#f1ede8',
        'surface-container-high': '#ebe8e3',
        'surface-container-highest': '#e6e2dd',
        'surface-variant': '#e6e2dd',
        'inverse-surface': '#31302d',
        'inverse-on-surface': '#f4f0eb',
        'on-background': '#1c1c19',
        'on-surface': '#1c1c19',
        'on-surface-variant': '#56423e',
        outline: '#89726d',
        'outline-variant': '#dcc1ba',
        primary: '#943d28',
        'primary-hover': '#7d2c18',
        'on-primary': '#ffffff',
        'primary-container': '#ffdad2',
        'on-primary-container': '#3d0700',
        'primary-fixed': '#ffdad2',
        'primary-fixed-dim': '#ffb4a3',
        'on-primary-fixed': '#3d0700',
        'on-primary-fixed-variant': '#7d2c18',
        'inverse-primary': '#ffb4a3',
        'surface-tint': '#9c432d',
        secondary: '#466550',
        'on-secondary': '#ffffff',
        'secondary-container': '#c8ebd0',
        'on-secondary-container': '#022110',
        'secondary-fixed': '#c8ebd0',
        'secondary-fixed-dim': '#adcfb4',
        'on-secondary-fixed': '#022110',
        'on-secondary-fixed-variant': '#2f4d39',
        tertiary: '#956800',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#ffdeac',
        'on-tertiary-container': '#281900',
        success: '#466550',
        'on-success': '#ffffff',
        'success-container': '#c8ebd0',
        'on-success-container': '#022110',
        warning: '#956800',
        'on-warning': '#ffffff',
        'warning-container': '#ffdeac',
        'on-warning-container': '#281900',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
      },
      boxShadow: {
        soft: '0 1px 2px rgba(86, 66, 62, 0.05), 0 8px 28px rgba(86, 66, 62, 0.08)',
        'soft-md': '0 10px 30px rgba(86, 66, 62, 0.10)',
        'soft-lg': '0 18px 46px rgba(86, 66, 62, 0.13)',
        'soft-xl': '0 28px 70px rgba(86, 66, 62, 0.18)',
        card: '0 8px 28px rgba(86, 66, 62, 0.08)',
        glow: '0 0 0 4px rgba(148, 61, 40, 0.10)',
        'inner-soft': 'inset 0 1px 3px rgba(61, 7, 0, 0.10)',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
        '3xl': '64px',
        gutter: '24px',
        'margin-mobile': '20px',
        'margin-desktop': '40px',
        unit: '4px',
      },
      fontFamily: {
        sans: ['Be Vietnam Pro', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['Literata', 'Georgia', 'serif'],
        'display-lg': ['Literata', 'Georgia', 'serif'],
        'headline-lg': ['Literata', 'Georgia', 'serif'],
        'headline-md': ['Literata', 'Georgia', 'serif'],
        'title-lg': ['Literata', 'Georgia', 'serif'],
        'body-lg': ['Be Vietnam Pro', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'body-md': ['Be Vietnam Pro', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'body-sm': ['Be Vietnam Pro', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'label-md': ['Be Vietnam Pro', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'label-sm': ['Be Vietnam Pro', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.01em' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600', letterSpacing: '0.005em' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'title-lg': ['20px', { lineHeight: '26px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '30px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '54px', fontWeight: '800' }],
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.96)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
        'fade-up': 'fade-up 0.45s cubic-bezier(0.4, 0, 0.2, 1) both',
        'scale-in': 'scale-in 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [],
};
