import { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import Dialog from '@mui/material/Dialog';
import DialogContent from '@mui/material/DialogContent';
import { CalendarDays, Check, Clock3, Dumbbell, MapPin, Plus, UsersRound } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import StatusBadge from '../components/StatusBadge';
import useApiData from '../hooks/useApiData';
import api from '../services/api';
import { showToast } from '../store/uiSlice';
import { asList } from '../utils/apiData';

const facilityColors=['from-blue-600 to-indigo-700','from-emerald-600 to-teal-700','from-orange-500 to-rose-600'];

export default function BookingsPage(){
  const role=useSelector(s=>s.auth.user?.role);
  const {data:facilities,setData:setFacilities}=useApiData('/facilities',[]);
  const {data:bookingData,setData:setBookings}=useApiData(role==='Resident'?'/bookings/my':'/bookings',[]);
  const list=asList(facilities);
  const bookings=asList(bookingData);
  const [selected,setSelected]=useState(null);
  const [form,setForm]=useState({date:'',start:'18:00',end:'19:00',attendees:2,purpose:''});
  const [facilityOpen,setFacilityOpen]=useState(false);
  const [facilityForm,setFacilityForm]=useState({name:'',type:'clubhouse',description:'',capacity:'20',openStart:'06:00',openEnd:'22:00',amenities:''});
  const dispatch=useDispatch();
  const book=async(e)=>{e.preventDefault();const payload={facilityId:selected._id,slotStart:new Date(`${form.date}T${form.start}`).toISOString(),slotEnd:new Date(`${form.date}T${form.end}`).toISOString(),attendees:Number(form.attendees),purpose:form.purpose};try{const {data:r}=await api.post('/bookings',payload);setBookings([r.data,...bookings]);setSelected(null);dispatch(showToast({message:'Booking request submitted'}));}catch(err){dispatch(showToast({message:err.response?.data?.message||'Booking request failed',severity:'error'}));}};
  const approve=async(b,action)=>{try{const {data:r}=await api.patch(`/bookings/${b._id}/approve`,{action});setBookings(bookings.map(x=>x._id===b._id?{...x,...r.data}:x));dispatch(showToast({message:`Booking ${action==='approve'?'approved':'rejected'}`}));}catch(err){dispatch(showToast({message:err.response?.data?.message||'Booking could not be updated',severity:'error'}));}};
  const createFacility=async(e)=>{e.preventDefault();const payload={name:facilityForm.name,type:facilityForm.type,description:facilityForm.description,capacity:Number(facilityForm.capacity),openHours:{start:facilityForm.openStart,end:facilityForm.openEnd},amenities:facilityForm.amenities.split(',').map(x=>x.trim()).filter(Boolean)};try{const {data:r}=await api.post('/facilities',payload);setFacilities([r.data,...list]);setFacilityOpen(false);setFacilityForm({name:'',type:'clubhouse',description:'',capacity:'20',openStart:'06:00',openEnd:'22:00',amenities:''});dispatch(showToast({message:'Facility created'}));}catch(err){dispatch(showToast({message:err.response?.data?.message||'Facility could not be created',severity:'error'}));}};
  return <><PageHeader eyebrow="Community amenities" title={role==='Resident'?'Find your perfect slot':'Facility & booking management'} description="Discover community spaces, choose a time and keep every reservation organized." action={role!=='Resident'?<button onClick={()=>setFacilityOpen(true)} className="btn-primary"><Plus size={18}/> Add facility</button>:null}/>
    <div className="grid gap-5 lg:grid-cols-3">{list.map((f,i)=><article key={f._id} className="card overflow-hidden"><div className={`flex h-40 items-end bg-gradient-to-br ${facilityColors[i%3]} p-5 text-white`}><div><div className="mb-2 inline-flex rounded-full bg-white/15 px-3 py-1 text-xs font-bold capitalize">{f.type}</div><h2 className="font-display text-2xl font-extrabold">{f.name}</h2></div></div><div className="p-5"><p className="min-h-10 text-sm text-slate-500">{f.description}</p><div className="mt-4 flex gap-5 text-xs text-slate-500"><span className="flex items-center gap-1"><UsersRound size={15}/> {f.capacity}</span><span className="flex items-center gap-1"><Clock3 size={15}/> {f.openHours?.start}–{f.openHours?.end}</span></div><div className="mt-4 flex flex-wrap gap-2">{f.amenities?.slice(0,3).map(a=><span key={a} className="rounded-full bg-slate-100 px-3 py-1 text-xs dark:bg-slate-800">{a}</span>)}</div>{role==='Resident'&&<button onClick={()=>setSelected(f)} className="btn-primary mt-5 w-full">Book a slot</button>}</div></article>)}</div>
    <section className="card mt-7 overflow-hidden"><div className="p-5"><h2 className="section-title">{role==='Resident'?'My booking history':'Booking requests'}</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400 dark:bg-slate-900"><tr><th className="px-5 py-3">Facility</th><th>Date & time</th><th>Purpose</th><th>Status</th>{role!=='Resident'&&<th>Action</th>}</tr></thead><tbody>{bookings.map(b=><tr key={b._id} className="border-t border-slate-100 dark:border-slate-800"><td className="px-5 py-4 font-bold">{b.facility?.name||'Community Facility'}</td><td>{new Date(b.slotStart).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</td><td>{b.purpose||'—'}</td><td><StatusBadge value={b.status}/></td>{role!=='Resident'&&<td className="space-x-3">{b.status==='pending'?<><button onClick={()=>approve(b,'approve')} className="font-bold text-emerald-600">Approve</button><button onClick={()=>approve(b,'reject')} className="font-bold text-red-500">Reject</button></>:'—'}</td>}</tr>)}</tbody></table></div></section>
    <Dialog open={!!selected} onClose={()=>setSelected(null)} fullWidth maxWidth="sm"><DialogContent className="!p-7"><div className="eyebrow">Reserve your time</div><h2 className="mt-2 font-display text-2xl font-extrabold">{selected?.name}</h2><form onSubmit={book} className="mt-6 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">Date</span><input required min={new Date().toISOString().split('T')[0]} type="date" className="field" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label><span className="mb-2 block text-sm font-bold">Start</span><input type="time" className="field" value={form.start} onChange={e=>setForm({...form,start:e.target.value})}/></label><label><span className="mb-2 block text-sm font-bold">End</span><input type="time" className="field" value={form.end} onChange={e=>setForm({...form,end:e.target.value})}/></label><label><span className="mb-2 block text-sm font-bold">Attendees</span><input type="number" min="1" className="field" value={form.attendees} onChange={e=>setForm({...form,attendees:e.target.value})}/></label><label><span className="mb-2 block text-sm font-bold">Purpose</span><input className="field" value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})}/></label><button className="btn-primary sm:col-span-2"><CalendarDays size={18}/> Request booking</button></form></DialogContent></Dialog>
    <Dialog open={facilityOpen} onClose={()=>setFacilityOpen(false)} fullWidth maxWidth="sm"><DialogContent className="!p-7"><h2 className="font-display text-2xl font-extrabold">Add facility</h2><form onSubmit={createFacility} className="mt-6 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">Name</span><input required className="field" value={facilityForm.name} onChange={e=>setFacilityForm({...facilityForm,name:e.target.value})}/></label><label><span className="mb-2 block text-sm font-bold">Type</span><select className="field" value={facilityForm.type} onChange={e=>setFacilityForm({...facilityForm,type:e.target.value})}>{['gym','pool','clubhouse','tennis-court','playground','party-hall','conference-room','other'].map(x=><option key={x}>{x}</option>)}</select></label><label><span className="mb-2 block text-sm font-bold">Capacity</span><input required min="1" type="number" className="field" value={facilityForm.capacity} onChange={e=>setFacilityForm({...facilityForm,capacity:e.target.value})}/></label><label><span className="mb-2 block text-sm font-bold">Opens</span><input type="time" className="field" value={facilityForm.openStart} onChange={e=>setFacilityForm({...facilityForm,openStart:e.target.value})}/></label><label><span className="mb-2 block text-sm font-bold">Closes</span><input type="time" className="field" value={facilityForm.openEnd} onChange={e=>setFacilityForm({...facilityForm,openEnd:e.target.value})}/></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">Amenities</span><input className="field" placeholder="AC, Projector, Wi-Fi" value={facilityForm.amenities} onChange={e=>setFacilityForm({...facilityForm,amenities:e.target.value})}/></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">Description</span><textarea required rows="3" className="field" value={facilityForm.description} onChange={e=>setFacilityForm({...facilityForm,description:e.target.value})}/></label><button className="btn-primary sm:col-span-2"><Plus size={18}/> Create facility</button></form></DialogContent></Dialog></>;
}
